package com.thinkgem.jeesite.common.constant;

public enum DeedEnum {
	M_A_SL_BRAND_ADD, M_A_SL_BRAND_SAVE, M_A_SL_BRAND_PHOTO, M_A_SL_BRAND_PRICE, S_A_MG_FREEZE, S_A_MG_BLACKLIST, S_A_MG_STATE, M_A_SL_MAT_TOP, M_A_TC_VERIFICATION_MARK, M_A_TS_MAT_SEARCH, M_A_TS_BASE_SAVE, M_A_TS_PARA_SAVE, M_A_TS_STANDARD_INFO_SAVE, M_A_TS_STANDARD_ITEM_SAVE, M_A_TS_ATTR_ITEM
}
